apiVersion: v2
appVersion: "1.0"
description: A Helm chart for opal-external-api App
name: opal-external-api
home: https://github.com/hmcts/opal-external-api
version: 0.0.20
maintainers:
  - name: HMCTS opal team
dependencies:
  - name: java
    version: 5.3.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
